baseURL = "/"
languageCode = "en-us"
title = "Hoome-cn"
theme = "HoomeTheme"
paginate = 6

copyright = "宁波灏米信息科技有限公司"

[params]
    dateFormat = "2022-09-16"
    icpID = "浙ICP备2022027034号-1"
    icpURL = "https://beian.miit.gov.cn/#/Integrated/index"


# Main Menu
[[menu.main]]
name = "首页"
url = ""
weight = 1
[[menu.main]]
name = "关于灏米"
url = "about"
weight = 2
[[menu.main]]
name = "产品展示"
url = "product"
weight = 3
[[menu.main]]
name = "联系我们"
url = "contact"
weight = 4
[[menu.main]]
name = "加入我们"
url = "https://talent.hoomenology.com/"
weight = 5

# Footer menu
[[menu.footer]]
name = "Über uns"
URL = "about"
weight = 1

[[menu.footer]]
name = "Projekt"
URL = "project"
weight = 2

[[menu.footer]]
name = "Dienstleistung"
URL = "service"
weight = 3

[[menu.footer]]
name = "Preise"
URL = "pricing"
weight = 4

[[menu.footer]]
name = "Häufige Fragen"
URL = "faq"
weight = 5

[[menu.footer]]
name = "Kontakt"
URL = "contact"
weight = 6


